image:
  - Ubuntu
  - Visual Studio 2019

build: off

artifacts:
  - path: TinyTeX*.tar.gz
    name: Linux binaries
  - path: TinyTeX*.tgz
    name: macOS binaries
  - path: TinyTeX*.zip
    name: Windows binaries
  - path: installer-unix*
    name: Installer for Unix
  - path: tinitex*
    name: The tinitex command
  - path: choco.zip
    name: Chocolatey log

deploy:
- provider: GitHub
  tag: v${CURRENT_TAG}
  release: TinyTeX v${CURRENT_TAG}
  description: >
    `TinyTeX-0` contains the `infraonly` scheme of TeX Live, without any LaTeX
    packages. `TinyTeX-1` contains enough LaTeX packages to compile R Markdown
    documents. `TinyTeX` contains even more LaTeX packages. The `zip` packages
    are for Windows. The `tgz` packages are for macOS. The `tar.gz` packages are
    for Linux. Please see https://github.com/yihui/tinytex-releases for more info.
  auth_token:
    secure: 7J9/ZS/EeHhAuxS+mtlT7mPKyLSEmXHRXK1fhBGSptLTmcIFqTbdRHRcTcgEB89n
  on:
    TINYTEX_RELEASE: true
- provider: GitHub
  tag: daily
  release: TinyTeX daily build
  description: >
    This release contains the daily build of TinyTeX. Please see
    https://github.com/yihui/tinytex-releases for more info.
  prerelease: true
  force_update: true
  auth_token:
    secure: 7J9/ZS/EeHhAuxS+mtlT7mPKyLSEmXHRXK1fhBGSptLTmcIFqTbdRHRcTcgEB89n
  on:
    TINYTEX_RELEASE: ""

for:
-
  matrix:
    only:
      - image: Ubuntu
  branches:
    only:
      - master
  skip_tags: true


  install:
    - "[ ! -z ${GH_KEY} ] || exit 0"
    - |
      eval "$(ssh-agent -s)"
      echo ${GH_KEY} | base64 -d > ~/id_rsa
      chmod 0600 ~/id_rsa
      ssh-add ~/id_rsa
      git config user.email "xie@yihui.name"
      git config user.name "Yihui Xie"
    - export CURRENT_TAG=$(date "+%Y.%m")$TINYTEX_PATCH_VERSION
    # if the tag must exist, download and exit (deploy the daily build)
    - |
      if [ $(git tag -l "v${CURRENT_TAG}") ]; then
        CURRENT_TAG=""
      fi
    - ./download.sh
    - |
      if [ -z $CURRENT_TAG ]; then
        git push --delete git@github.com:${APPVEYOR_REPO_NAME}.git daily
        git tag -f daily  # force tag the current commit to be 'daily'
      else
        export TINYTEX_RELEASE=true
        sed -i -E "s|(\s*<version>)([0-9.]+)(</version>\s*)|\1${CURRENT_TAG}\3|" choco/tinytex.nuspec
        sed -i -E "s|(\s*checksum\s*=\s*')([0-9a-f]{32})('\\s*)|\1$(md5sum TinyTeX-1-v${CURRENT_TAG}.zip | cut -d' ' -f1)\3|" choco/tools/chocolateyinstall.ps1
        git add -u
        git diff-index --quiet HEAD && exit 0 || git commit -m"TinyTeX release v${CURRENT_TAG}"
        git tag -f v${CURRENT_TAG}  # actually tag this commit
      fi
      git push --tags git@github.com:${APPVEYOR_REPO_NAME}.git HEAD

-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    - cd choco
    - choco pack
    - choco install --no-progress tinytex -source "'.;https://chocolatey.org/api/v2/'"
    - choco uninstall -y tinytex
    - 7z a ../choco.zip C:\ProgramData\chocolatey\logs\chocolatey.log
    - ps: |
        if ($Env:APPVEYOR_REPO_TAG_NAME -eq "daily") {
          Exit-AppVeyorBuild
        }
        if ($Env:APPVEYOR_REPO_TAG -eq "true") {
          choco apikey --key $Env:CHOCO_KEY --source https://push.chocolatey.org/
          choco push --source https://push.chocolatey.org/
        }
